#%RAML 1.0
title: testAPI
version: v1

/cust1:
  description: This is customer one details
  displayName: CUST_1 Details
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "Name": "Aravinthan"
              }

                                